# Generated by Django 6.0.3 on 2026-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_birth_date_profile_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Mô tả'),
            preserve_default=False,
        ),
    ]
