# Generated by Django 6.0.3 on 2026-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_year_profile_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificate',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
