# Generated by Django 6.0.3 on 2026-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
