# Generated by Django 6.0.3 on 2026-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_skill_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Analytics', 'Analytics'), ('FinTech', 'FinTech'), ('Tools', 'Tools')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=80),
        ),
    ]
